server:
  port: 3000

spring:
  # 데이터 베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: PROJECT
    password: _aA123456

  # 파일 업로드 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 40MB

  # 정적 자원 설정(CSS, JS, 이미지)
  resource:
    staticLocations: file:src/main/resource/static/

  # 라이브 리로드 설정(배포 시 제거 필수)
  devtools:
    livereload:
      enable: true

  # 타임리프 설정(배포시 prefix 변경 필수)
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

file:
  upload:
    path: C:/uploads/
    url: /uploads/

# 로거 설정
logging:
  level:
    org:
      springframework:
        jdbc: trace